//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "../../../../../govard/internal/desktop/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "onboarding:progress": $$createType0,
        "operations:notification": $$createType1,
        "sync:started": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = desktop$0.OnboardingProgressPayload.createFrom;
const $$createType1 = desktop$0.OperationNotification.createFrom;
const $$createType2 = desktop$0.SyncStartedPayload.createFrom;

configure();
