// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as desktop$0 from "../../../../../govard/internal/desktop/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "global-logs:error": string;
            "global-logs:line": string;
            "global-logs:status": string;
            "logs:error": string;
            "logs:line": string;
            "logs:status": string;
            "onboarding:progress": desktop$0.OnboardingProgressPayload;
            "operations:notification": desktop$0.OperationNotification;
            "sync:completed": string;
            "sync:failed": string;
            "sync:output": string;
            "sync:started": desktop$0.SyncStartedPayload;
        }
    }
}
