// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvironmentService handles dashboard data and project lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} projectQuery
 * @returns {$CancellablePromise<string>}
 */
export function DeleteProject(projectQuery) {
    return $Call.ByID(1866001717, projectQuery);
}

/**
 * @returns {$CancellablePromise<$models.Dashboard>}
 */
export function GetDashboard() {
    return $Call.ByID(662956515).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} project
 * @returns {$CancellablePromise<string>}
 */
export function GetEnvironmentURL(project) {
    return $Call.ByID(2531940939, project);
}

/**
 * ListFrameworks returns every framework registered in internal/frameworks,
 * for the onboarding UI's framework picker. This keeps the frontend's
 * dropdown, alias resolution, and display-name formatting in sync with the
 * Go-side registry instead of duplicating framework metadata in JS.
 * @returns {$CancellablePromise<$models.FrameworkOption[]>}
 */
export function ListFrameworks() {
    return $Call.ByID(2571085722).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function OpenDocs(path) {
    return $Call.ByID(3666528904, path);
}

/**
 * OpenEnvironment resolves the project URL and hands it to the OS browser.
 * The frontend shows its own success toast, so the returned string is only a
 * fallback message.
 * @param {string} project
 * @returns {$CancellablePromise<string>}
 */
export function OpenEnvironment(project) {
    return $Call.ByID(466494344, project);
}

/**
 * @param {string} project
 * @returns {$CancellablePromise<string>}
 */
export function PullEnvironment(project) {
    return $Call.ByID(410454013, project);
}

/**
 * @param {string} action
 * @returns {$CancellablePromise<string>}
 */
export function QuickAction(action) {
    return $Call.ByID(273718460, action);
}

/**
 * @param {string} action
 * @param {string} project
 * @returns {$CancellablePromise<string>}
 */
export function QuickActionForProject(action, project) {
    return $Call.ByID(3389507184, action, project);
}

/**
 * @param {string} project
 * @returns {$CancellablePromise<string>}
 */
export function RestartEnvironment(project) {
    return $Call.ByID(773330695, project);
}

/**
 * @param {string} project
 * @returns {$CancellablePromise<string>}
 */
export function StartEnvironment(project) {
    return $Call.ByID(2944376646, project);
}

/**
 * @param {string} project
 * @returns {$CancellablePromise<string>}
 */
export function StopEnvironment(project) {
    return $Call.ByID(3743652420, project);
}

/**
 * @param {string} project
 * @returns {$CancellablePromise<string>}
 */
export function ToggleEnvironment(project) {
    return $Call.ByID(3540647888, project);
}

// Private type creation functions
const $$createType0 = $models.Dashboard.createFrom;
const $$createType1 = $models.FrameworkOption.createFrom;
const $$createType2 = $Create.Array($$createType1);
