// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GlobalServiceService handles global Govard service management.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.GlobalServicesSnapshot>}
 */
export function GetGlobalServices() {
    return $Call.ByID(903572799).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} serviceID
 * @returns {$CancellablePromise<string>}
 */
export function OpenGlobalService(serviceID) {
    return $Call.ByID(2394706306, serviceID);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function PullGlobalServices() {
    return $Call.ByID(3196261548);
}

/**
 * @param {string} serviceID
 * @returns {$CancellablePromise<string>}
 */
export function RestartGlobalService(serviceID) {
    return $Call.ByID(244015971, serviceID);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function RestartGlobalServices() {
    return $Call.ByID(4117557808);
}

/**
 * @param {string} serviceID
 * @returns {$CancellablePromise<string>}
 */
export function StartGlobalService(serviceID) {
    return $Call.ByID(4143521014, serviceID);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function StartGlobalServices() {
    return $Call.ByID(1328014687);
}

/**
 * @param {string} serviceID
 * @returns {$CancellablePromise<string>}
 */
export function StopGlobalService(serviceID) {
    return $Call.ByID(1906961010, serviceID);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function StopGlobalServices() {
    return $Call.ByID(4017840019);
}

// Private type creation functions
const $$createType0 = $models.GlobalServicesSnapshot.createFrom;
