// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService handles log streaming and terminal sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} serviceID
 * @param {number} lines
 * @returns {$CancellablePromise<string>}
 */
export function GetGlobalServiceLogs(serviceID, lines) {
    return $Call.ByID(3122740469, serviceID, lines);
}

/**
 * @param {string} project
 * @param {number} lines
 * @returns {$CancellablePromise<string>}
 */
export function GetLogs(project, lines) {
    return $Call.ByID(436647391, project, lines);
}

/**
 * @param {string} project
 * @param {string} service
 * @param {number} lines
 * @returns {$CancellablePromise<string>}
 */
export function GetLogsForService(project, service, lines) {
    return $Call.ByID(81661777, project, service, lines);
}

/**
 * LogService.SaveLogsToFile writes the frontend's log buffer through the
 * platform save dialog. The free function below keeps its own signature so the
 * contract stays testable without a service.
 * @param {string} content
 * @param {string} suggestedName
 * @returns {$CancellablePromise<string>}
 */
export function SaveLogsToFile(content, suggestedName) {
    return $Call.ByID(2539934021, content, suggestedName);
}

/**
 * @param {string} serviceID
 * @returns {$CancellablePromise<string>}
 */
export function StartGlobalServiceLogStream(serviceID) {
    return $Call.ByID(893848252, serviceID);
}

/**
 * @param {string} project
 * @returns {$CancellablePromise<string>}
 */
export function StartLogStream(project) {
    return $Call.ByID(4126401894, project);
}

/**
 * @param {string} project
 * @param {string} service
 * @returns {$CancellablePromise<string>}
 */
export function StartLogStreamForService(project, service) {
    return $Call.ByID(1617905692, project, service);
}

/**
 * @param {string} project
 * @param {string} service
 * @param {string} user
 * @param {string} shell
 * @returns {$CancellablePromise<string>}
 */
export function StartServiceTerminalInOS(project, service, user, shell) {
    return $Call.ByID(900987954, project, service, user, shell);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function StopGlobalServiceLogStream() {
    return $Call.ByID(3830432576);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function StopLogStream() {
    return $Call.ByID(3326070746);
}
