// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Dashboard {
    /**
     * Creates a new Dashboard instance.
     * @param {Partial<Dashboard>} [$$source = {}] - The source object to create the Dashboard.
     */
    constructor($$source = {}) {
        if (!("activeEnvironments" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeEnvironments"] = 0;
        }
        if (!("runningServices" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["runningServices"] = 0;
        }
        if (!("queuedTasks" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["queuedTasks"] = 0;
        }
        if (!("activeSummary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeSummary"] = "";
        }
        if (!("servicesSummary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["servicesSummary"] = "";
        }
        if (!("queueSummary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["queueSummary"] = "";
        }
        if (!("environments" in $$source)) {
            /**
             * @member
             * @type {Environment[]}
             */
            this["environments"] = [];
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dashboard instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Dashboard}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("environments" in $$parsedSource) {
            $$parsedSource["environments"] = $$createField6_0($$parsedSource["environments"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField7_0($$parsedSource["warnings"]);
        }
        return new Dashboard(/** @type {Partial<Dashboard>} */($$parsedSource));
    }
}

export class DesktopSettings {
    /**
     * Creates a new DesktopSettings instance.
     * @param {Partial<DesktopSettings>} [$$source = {}] - The source object to create the DesktopSettings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("proxyTarget" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyTarget"] = "";
        }
        if (!("preferredBrowser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preferredBrowser"] = "";
        }
        if (!("codeEditor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["codeEditor"] = "";
        }
        if (!("dbClientPreference" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dbClientPreference"] = "";
        }
        if (!("runInBackground" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["runInBackground"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DesktopSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSettings(/** @type {Partial<DesktopSettings>} */($$parsedSource));
    }
}

export class Environment {
    /**
     * Creates a new Environment instance.
     * @param {Partial<Environment>} [$$source = {}] - The source object to create the Environment.
     */
    constructor($$source = {}) {
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project"] = "";
        }
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["extraDomains"] = undefined;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("framework" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["framework"] = "";
        }
        if (!("technologies" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["technologies"] = [];
        }
        if (!("php" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["php"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("services" in $$source)) {
            /**
             * @member
             * @type {Service[]}
             */
            this["services"] = [];
        }
        if (!("serviceTargets" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["serviceTargets"] = [];
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["syncingRemote"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["gitBranch"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["envVars"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Environment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Environment}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        const $$createField8_0 = $$createType4;
        const $$createField9_0 = $$createType2;
        const $$createField13_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extraDomains" in $$parsedSource) {
            $$parsedSource["extraDomains"] = $$createField2_0($$parsedSource["extraDomains"]);
        }
        if ("technologies" in $$parsedSource) {
            $$parsedSource["technologies"] = $$createField5_0($$parsedSource["technologies"]);
        }
        if ("services" in $$parsedSource) {
            $$parsedSource["services"] = $$createField8_0($$parsedSource["services"]);
        }
        if ("serviceTargets" in $$parsedSource) {
            $$parsedSource["serviceTargets"] = $$createField9_0($$parsedSource["serviceTargets"]);
        }
        if ("envVars" in $$parsedSource) {
            $$parsedSource["envVars"] = $$createField13_0($$parsedSource["envVars"]);
        }
        return new Environment(/** @type {Partial<Environment>} */($$parsedSource));
    }
}

/**
 * FrameworkOption describes one selectable framework for the onboarding UI,
 * sourced from the internal/frameworks registry so the frontend never
 * hardcodes framework metadata independently of the Go-side definitions.
 */
export class FrameworkOption {
    /**
     * Creates a new FrameworkOption instance.
     * @param {Partial<FrameworkOption>} [$$source = {}] - The source object to create the FrameworkOption.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("aliases" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["aliases"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrameworkOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FrameworkOption}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("aliases" in $$parsedSource) {
            $$parsedSource["aliases"] = $$createField2_0($$parsedSource["aliases"]);
        }
        return new FrameworkOption(/** @type {Partial<FrameworkOption>} */($$parsedSource));
    }
}

export class GlobalService {
    /**
     * Creates a new GlobalService instance.
     * @param {Partial<GlobalService>} [$$source = {}] - The source object to create the GlobalService.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("composeService" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["composeService"] = "";
        }
        if (!("containerName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["containerName"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("health" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["health"] = "";
        }
        if (!("statusText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusText"] = "";
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("openable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["openable"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalService instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GlobalService}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlobalService(/** @type {Partial<GlobalService>} */($$parsedSource));
    }
}

export class GlobalServicesSnapshot {
    /**
     * Creates a new GlobalServicesSnapshot instance.
     * @param {Partial<GlobalServicesSnapshot>} [$$source = {}] - The source object to create the GlobalServicesSnapshot.
     */
    constructor($$source = {}) {
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["active"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("services" in $$source)) {
            /**
             * @member
             * @type {GlobalService[]}
             */
            this["services"] = [];
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalServicesSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GlobalServicesSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("services" in $$parsedSource) {
            $$parsedSource["services"] = $$createField3_0($$parsedSource["services"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField4_0($$parsedSource["warnings"]);
        }
        return new GlobalServicesSnapshot(/** @type {Partial<GlobalServicesSnapshot>} */($$parsedSource));
    }
}

export class OnboardInput {
    /**
     * Creates a new OnboardInput instance.
     * @param {Partial<OnboardInput>} [$$source = {}] - The source object to create the OnboardInput.
     */
    constructor($$source = {}) {
        if (!("projectPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectPath"] = "";
        }
        if (!("framework" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["framework"] = "";
        }
        if (!("frameworkVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["frameworkVersion"] = "";
        }
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("cloneFromGit" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cloneFromGit"] = false;
        }
        if (!("gitProtocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gitProtocol"] = "";
        }
        if (!("gitURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gitURL"] = "";
        }
        if (!("confirmFolderOverride" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmFolderOverride"] = false;
        }
        if (!("varnishEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["varnishEnabled"] = false;
        }
        if (!("redisEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["redisEnabled"] = false;
        }
        if (!("rabbitMQEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["rabbitMQEnabled"] = false;
        }
        if (!("elasticsearchEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["elasticsearchEnabled"] = false;
        }
        if (!("applyOverrides" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["applyOverrides"] = false;
        }
        if (!("skipIDE" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["skipIDE"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OnboardInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OnboardInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OnboardInput(/** @type {Partial<OnboardInput>} */($$parsedSource));
    }
}

/**
 * OnboardingProgressPayload replaces the map[string]string
 * onboarding:progress payload with byte-identical JSON.
 */
export class OnboardingProgressPayload {
    /**
     * Creates a new OnboardingProgressPayload instance.
     * @param {Partial<OnboardingProgressPayload>} [$$source = {}] - The source object to create the OnboardingProgressPayload.
     */
    constructor($$source = {}) {
        if (!("step" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["step"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OnboardingProgressPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OnboardingProgressPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OnboardingProgressPayload(/** @type {Partial<OnboardingProgressPayload>} */($$parsedSource));
    }
}

/**
 * OperationNotification is emitted to the frontend when a tracked operation finishes.
 */
export class OperationNotification {
    /**
     * Creates a new OperationNotification instance.
     * @param {Partial<OperationNotification>} [$$source = {}] - The source object to create the OperationNotification.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("operation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operation"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["project"] = undefined;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationNotification instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OperationNotification}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OperationNotification(/** @type {Partial<OperationNotification>} */($$parsedSource));
    }
}

export class RemoteEntry {
    /**
     * Creates a new RemoteEntry instance.
     * @param {Partial<RemoteEntry>} [$$source = {}] - The source object to create the RemoteEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastSync"] = undefined;
        }
        if (!("protected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["protected"] = false;
        }
        if (!("authMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authMethod"] = "";
        }
        if (!("capabilities" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["capabilities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteEntry}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField8_0($$parsedSource["capabilities"]);
        }
        return new RemoteEntry(/** @type {Partial<RemoteEntry>} */($$parsedSource));
    }
}

export class RemoteSnapshot {
    /**
     * Creates a new RemoteSnapshot instance.
     * @param {Partial<RemoteSnapshot>} [$$source = {}] - The source object to create the RemoteSnapshot.
     */
    constructor($$source = {}) {
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project"] = "";
        }
        if (!("remotes" in $$source)) {
            /**
             * @member
             * @type {RemoteEntry[]}
             */
            this["remotes"] = [];
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("remotes" in $$parsedSource) {
            $$parsedSource["remotes"] = $$createField1_0($$parsedSource["remotes"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new RemoteSnapshot(/** @type {Partial<RemoteSnapshot>} */($$parsedSource));
    }
}

export class Service {
    /**
     * Creates a new Service instance.
     * @param {Partial<Service>} [$$source = {}] - The source object to create the Service.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["port"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["target"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Service instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Service}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Service(/** @type {Partial<Service>} */($$parsedSource));
    }
}

/**
 * SyncStartedPayload replaces the map[string]string sync:started payload with
 * byte-identical JSON.
 */
export class SyncStartedPayload {
    /**
     * Creates a new SyncStartedPayload instance.
     * @param {Partial<SyncStartedPayload>} [$$source = {}] - The source object to create the SyncStartedPayload.
     */
    constructor($$source = {}) {
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project"] = "";
        }
        if (!("remote" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remote"] = "";
        }
        if (!("preset" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preset"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncStartedPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncStartedPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncStartedPayload(/** @type {Partial<SyncStartedPayload>} */($$parsedSource));
    }
}

export class SystemMetrics {
    /**
     * Creates a new SystemMetrics instance.
     * @param {Partial<SystemMetrics>} [$$source = {}] - The source object to create the SystemMetrics.
     */
    constructor($$source = {}) {
        if (!("cpuUsage" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpuUsage"] = 0;
        }
        if (!("memoryUsage" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memoryUsage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemMetrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemMetrics(/** @type {Partial<SystemMetrics>} */($$parsedSource));
    }
}

/**
 * TrayStatus tells the Settings page whether "run in background" can actually
 * hide the window, which needs a tray to bring it back.
 */
export class TrayStatus {
    /**
     * Creates a new TrayStatus instance.
     * @param {Partial<TrayStatus>} [$$source = {}] - The source object to create the TrayStatus.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrayStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrayStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrayStatus(/** @type {Partial<TrayStatus>} */($$parsedSource));
    }
}

export class UpdateCheckResult {
    /**
     * Creates a new UpdateCheckResult instance.
     * @param {Partial<UpdateCheckResult>} [$$source = {}] - The source object to create the UpdateCheckResult.
     */
    constructor($$source = {}) {
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("outdated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["outdated"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("changelog" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["changelog"] = "";
        }
        if (!("channel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["channel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateCheckResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateCheckResult(/** @type {Partial<UpdateCheckResult>} */($$parsedSource));
    }
}

export class UserInfo {
    /**
     * Creates a new UserInfo instance.
     * @param {Partial<UserInfo>} [$$source = {}] - The source object to create the UserInfo.
     */
    constructor($$source = {}) {
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserInfo(/** @type {Partial<UserInfo>} */($$parsedSource));
    }
}

export class presetOptionDef {
    /**
     * Creates a new presetOptionDef instance.
     * @param {Partial<presetOptionDef>} [$$source = {}] - The source object to create the presetOptionDef.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("defaultValue" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["defaultValue"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new presetOptionDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {presetOptionDef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new presetOptionDef(/** @type {Partial<presetOptionDef>} */($$parsedSource));
    }
}

export class presetSyncOptions {
    /**
     * Creates a new presetSyncOptions instance.
     * @param {Partial<presetSyncOptions>} [$$source = {}] - The source object to create the presetSyncOptions.
     */
    constructor($$source = {}) {
        if (!("preset" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preset"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {presetOptionDef[]}
             */
            this["options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new presetSyncOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {presetSyncOptions}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField2_0($$parsedSource["options"]);
        }
        return new presetSyncOptions(/** @type {Partial<presetSyncOptions>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Environment.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = Service.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = GlobalService.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = RemoteEntry.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = presetOptionDef.createFrom;
const $$createType11 = $Create.Array($$createType10);
