// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OnboardingService handles project discovery and onboarding.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<string>}
 */
export function DetectMigrationSource(projectPath) {
    return $Call.ByID(1725097703, projectPath);
}

/**
 * @param {$models.OnboardInput} input
 * @returns {$CancellablePromise<string>}
 */
export function OnboardProject(input) {
    return $Call.ByID(2237882909, input);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function PickProjectDirectory() {
    return $Call.ByID(3953136504);
}
