// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RemoteService handles remote project management and synchronization.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} project
 * @returns {$CancellablePromise<$models.RemoteSnapshot>}
 */
export function GetRemotes(project) {
    return $Call.ByID(3404565501, project).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} project
 * @param {string} preset
 * @returns {$CancellablePromise<$models.presetSyncOptions>}
 */
export function GetSyncOptions(project, preset) {
    return $Call.ByID(78041085, project, preset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} project
 * @param {string} remoteName
 * @returns {$CancellablePromise<string>}
 */
export function OpenRemoteDB(project, remoteName) {
    return $Call.ByID(2221616490, project, remoteName);
}

/**
 * OpenRemoteSFTP and OpenRemoteShell pass s.ctx, not lifecycleContext(): for
 * these two the context is the "GUI runtime attached" signal that gates
 * launching a real terminal, so it must stay nil outside a running app. Tests
 * (and any pre-startup call) then take the URL fallback instead of opening a
 * terminal on the developer's desktop.
 * @param {string} project
 * @param {string} remoteName
 * @returns {$CancellablePromise<string>}
 */
export function OpenRemoteSFTP(project, remoteName) {
    return $Call.ByID(1932172449, project, remoteName);
}

/**
 * @param {string} project
 * @param {string} remoteName
 * @returns {$CancellablePromise<string>}
 */
export function OpenRemoteShell(project, remoteName) {
    return $Call.ByID(3487071762, project, remoteName);
}

/**
 * @param {string} project
 * @param {string} remoteName
 * @returns {$CancellablePromise<string>}
 */
export function OpenRemoteURL(project, remoteName) {
    return $Call.ByID(2573531345, project, remoteName);
}

/**
 * @param {string} project
 * @param {string} remoteName
 * @param {string} preset
 * @param {{ [_ in string]?: boolean }} options
 * @returns {$CancellablePromise<string>}
 */
export function RunRemoteSync(project, remoteName, preset, options) {
    return $Call.ByID(507222310, project, remoteName, preset, options);
}

/**
 * @param {string} project
 * @param {string} remoteName
 * @param {string} preset
 * @param {{ [_ in string]?: boolean }} options
 * @returns {$CancellablePromise<string>}
 */
export function RunRemoteSyncInTerminal(project, remoteName, preset, options) {
    return $Call.ByID(2878495869, project, remoteName, preset, options);
}

/**
 * @param {string} project
 * @param {string} remoteName
 * @param {string} preset
 * @param {{ [_ in string]?: boolean }} options
 * @returns {$CancellablePromise<string>}
 */
export function RunRemoteSyncPreset(project, remoteName, preset, options) {
    return $Call.ByID(3206548853, project, remoteName, preset, options);
}

/**
 * @param {string} project
 * @param {string} remoteName
 * @returns {$CancellablePromise<string>}
 */
export function TestRemote(project, remoteName) {
    return $Call.ByID(3478549464, project, remoteName);
}

// Private type creation functions
const $$createType0 = $models.RemoteSnapshot.createFrom;
const $$createType1 = $models.presetSyncOptions.createFrom;
