// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService handles user preferences and desktop settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetMailpitURL() {
    return $Call.ByID(1098421658);
}

/**
 * @returns {$CancellablePromise<$models.DesktopSettings>}
 */
export function GetSettings() {
    return $Call.ByID(2638684590).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.TrayStatus>}
 */
export function GetTrayStatus() {
    return $Call.ByID(2361133561).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ResetSettings() {
    return $Call.ByID(3011851361);
}

/**
 * @param {$models.DesktopSettings} settings
 * @returns {$CancellablePromise<string>}
 */
export function UpdateSettings(settings) {
    return $Call.ByID(555268093, settings);
}

// Private type creation functions
const $$createType0 = $models.DesktopSettings.createFrom;
const $$createType1 = $models.TrayStatus.createFrom;
