// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService handles system metrics and user information.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetResourceMetrics() {
    return $Call.ByID(2154490700);
}

/**
 * @returns {$CancellablePromise<$models.SystemMetrics>}
 */
export function GetSystemMetrics() {
    return $Call.ByID(2261945243).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.UserInfo>}
 */
export function GetUserInfo() {
    return $Call.ByID(3619931808).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(346261521);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(1457209326);
}

// Private type creation functions
const $$createType0 = $models.SystemMetrics.createFrom;
const $$createType1 = $models.UserInfo.createFrom;
