// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes update checks, the update channel and self-restart
 * to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.UpdateCheckResult>}
 */
export function CheckForUpdates() {
    return $Call.ByID(697778984).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetUpdateChannel() {
    return $Call.ByID(881667841);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function InstallLatestUpdate() {
    return $Call.ByID(69193162);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function RestartDesktopApp() {
    return $Call.ByID(2129346863);
}

/**
 * @param {string} channel
 * @returns {$CancellablePromise<string>}
 */
export function SetUpdateChannel(channel) {
    return $Call.ByID(4265091045, channel);
}

// Private type creation functions
const $$createType0 = $models.UpdateCheckResult.createFrom;
