package tests

import (
	"testing"

	"govard/internal/desktop"
)

func TestDesktopPkgLooksLikeGovardForTest(t *testing.T) {
	t.Run("excludes proxy and warden namespaces", func(t *testing.T) {
		if desktop.LooksLikeGovardForTest("proxy", []string{"web"}, []string{"/home/kai/.govard/compose/proxy.yml"}, false) {
			t.Fatal("proxy project should never be treated as Govard workload")
		}
		if desktop.LooksLikeGovardForTest("warden", []string{"php"}, []string{"/opt/warden/docker-compose.yml"}, false) {
			t.Fatal("warden project should never be treated as Govard workload")
		}
	})

	t.Run("excludes non-govard compose projects with generic services", func(t *testing.T) {
		if desktop.LooksLikeGovardForTest(
			"shoplegacy",
			[]string{"web", "php", "db"},
			[]string{"/opt/warden/environments/shoplegacy/docker-compose.yml"},
			false,
		) {
			t.Fatal("non-govard compose projects should not be treated as Govard")
		}
	})

	t.Run("includes projects generated by govard compose renderer", func(t *testing.T) {
		if !desktop.LooksLikeGovardForTest(
			"m2govard",
			[]string{"web", "php", "db"},
			[]string{"/home/kai/.govard/compose/m2govard-c9d09835429f.yml"},
			false,
		) {
			t.Fatal("govard compose projects should be treated as Govard")
		}
	})

	t.Run("includes windows style govard compose path", func(t *testing.T) {
		if !desktop.LooksLikeGovardForTest(
			"m2govard",
			[]string{"web"},
			[]string{`C:\Users\kai\.govard\compose\m2.govard.yml`},
			false,
		) {
			t.Fatal("windows govard compose path should be treated as Govard")
		}
	})

	t.Run("includes projects with loaded govard config", func(t *testing.T) {
		if !desktop.LooksLikeGovardForTest("demo", []string{"nginx"}, []string{"/tmp/docker-compose.yml"}, true) {
			t.Fatal("projects with loaded govard config should be treated as Govard")
		}
	})
}
