{{ $queue := .Config.Stack.Services.Queue }}
{{ $queueVersion := .Config.Stack.QueueVersion }}
{{ if eq $queue "rabbitmq" }}
services:
  rabbitmq:
    image: {{ $.ImageRepository }}/rabbitmq:{{ $queueVersion }}
    networks:
      - govard-net
{{ end }}
