{{ $cache := .Config.Stack.Services.Cache }}
{{ $cacheVersion := .Config.Stack.CacheVersion }}
{{ if or (eq $cache "redis") (eq $cache "valkey") }}
services:
  redis:
    image: {{ if eq $cache "valkey" }}{{ $.ImageRepository }}/valkey:{{ $cacheVersion }}{{ else }}{{ $.ImageRepository }}/redis:{{ $cacheVersion }}{{ end }}
    networks:
      - govard-net
{{ end }}
