# Elasticsearch/OpenSearch service for search functionality
{{ $search := .Config.Stack.Services.Search }}
{{ $searchVersion := .Config.Stack.SearchVersion }}

services:
  {{ if or (eq $search "elasticsearch") (eq $search "opensearch") }}
  elasticsearch:
    image: {{ if eq $search "elasticsearch" }}{{ $.ImageRepository }}/elasticsearch:{{ $searchVersion }}{{ else }}{{ $.ImageRepository }}/opensearch:{{ $searchVersion }}{{ end }}

    environment:
      - discovery.type=single-node
      {{ if eq $search "elasticsearch" }}
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      {{ else }}
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
      {{ end }}
    networks:
      - govard-net
    volumes:
      - search-data:{{ if eq $search "elasticsearch" }}/usr/share/elasticsearch/data{{ else }}/usr/share/opensearch/data{{ end }}
  {{ end }}

volumes:
  {{ if or (eq $search "elasticsearch") (eq $search "opensearch") }}
  search-data:
  {{ end }}
