{{ $cache := .Config.Stack.Services.Cache }}
{{ $cacheVersion := .Config.Stack.CacheVersion }}
{{ if or (eq $cache "redis") (eq $cache "valkey") }}
services:
  redis:
    hostname: {{ .Config.ProjectName }}-redis
    image: {{ if eq $cache "valkey" }}{{ $.ImageRepository }}valkey:{{ $cacheVersion }}{{ else }}{{ $.ImageRepository }}redis:{{ $cacheVersion }}{{ end }}
    volumes:
      - cache-data{{ if .Config.Profile }}-{{ .Config.Profile }}{{ end }}:/data
    networks:
      - govard-net

volumes:
  cache-data{{ if .Config.Profile }}-{{ .Config.Profile }}{{ end }}:
{{ end }}
