{{ if .Config.Stack.Features.Queue }}
services:
  queue:
    image: {{ $.ImageRepository }}php:{{ .Config.Stack.PHPVersion }}
    volumes:
      - .:{{ .WorkDir }}
    command: php artisan queue:work --sleep=3 --tries=3
    networks:
      - govard-net
    depends_on:
      - db
{{ end }}
