# Magento 1/OpenMage Docker Compose configuration
# This is the main Docker Compose file for Magento 1 projects

services:
  web:
    image: {{ $.ImageRepository }}/nginx:{{ .Config.Stack.NginxVersion }}
    volumes:
      - .:/var/www/html
    networks:
      - govard-net
      - govard-proxy
    depends_on:
      - php
    environment:
      - NGINX_PUBLIC=
      - NGINX_TEMPLATE=magento1.conf

  php:
    image: {{ $.ImageRepository }}/php:{{ .Config.Stack.PHPVersion }}
    volumes:
      - .:/var/www/html
    networks:
      - govard-net
    environment:
      XDEBUG_MODE: off

  {{ if .Config.Stack.Features.Xdebug }}
  php-debug:
    image: {{ $.ImageRepository }}/php:{{ .Config.Stack.PHPVersion }}
    volumes:
      - .:/var/www/html
    networks:
      - govard-net
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal
  {{ end }}

  {{ if ne .Config.Stack.DBType "none" }}
  db:
    image: {{ $.ImageRepository }}/{{ .Config.Stack.DBType }}:{{ .Config.Stack.DBVersion }}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    networks:
      - govard-net
    volumes:
      - db-data:/var/lib/mysql
  {{ end }}

  {{ $cache := .Config.Stack.Services.Cache }}
  {{ $cacheVersion := .Config.Stack.CacheVersion }}
  {{ if or (eq $cache "redis") (eq $cache "valkey") }}
  redis:
    image: {{ if eq $cache "valkey" }}{{ $.ImageRepository }}/valkey:{{ $cacheVersion }}{{ else }}{{ $.ImageRepository }}/redis:{{ $cacheVersion }}{{ end }}
    networks:
      - govard-net
    {{ end }}

  {{ $queue := .Config.Stack.Services.Queue }}
  {{ $queueVersion := .Config.Stack.QueueVersion }}
  {{ if eq $queue "rabbitmq" }}
  rabbitmq:
    image: {{ $.ImageRepository }}/rabbitmq:{{ $queueVersion }}
    networks:
      - govard-net
    {{ end }}

networks:
  govard-net:
    driver: bridge
  govard-proxy:
    external: true

volumes:
  {{ if ne .Config.Stack.DBType "none" }}
  db-data:
  {{ end }}
