package magento1

import "govard/internal/engine"

// Manifest is Magento 1's FrameworkManifestConfig - registered into
// engine's runtime store by Definition() (via frameworks.Register),
// replacing the old "magento1" entry that used to live in
// internal/engine/framework_manifest.json's "frameworks" object. Shared
// with OpenMage (internal/frameworks/openmage/manifest.go references this
// value directly) since OpenMage shares Magento 1's database schema and
// sync/exclude shape byte-for-byte.
var Manifest = engine.FrameworkManifestConfig{
	Ignored: []string{
		"catalogsearch_fulltext",
		"catalogsearch_query",
		"catalogsearch_result",
		"core_session",
		"cron_schedule",
		"enterprise_logging_event",
		"enterprise_logging_event_changes",
		"index_event",
		"log_customer",
		"log_quote",
		"log_summary",
		"log_summary_type",
		"log_url",
		"log_url_info",
		"log_visitor",
		"log_visitor_info",
		"log_visitor_online",
		"mkp_api_session_vendor",
		"report_compared_product_index",
		"report_viewed_product_index",
		"smtppro_email_log",
		"udprod_images",
	},
	Sensitive: []string{
		"admin_user",
		"api_user",
		"customer_address_entity",
		"customer_address_entity_datetime",
		"customer_address_entity_decimal",
		"customer_address_entity_int",
		"customer_address_entity_text",
		"customer_address_entity_varchar",
		"customer_entity",
		"customer_entity_datetime",
		"customer_entity_decimal",
		"customer_entity_int",
		"customer_entity_text",
		"customer_entity_varchar",
		"newsletter_subscriber",
		"sales_flat_order",
		"sales_flat_order_address",
		"sales_flat_order_grid",
		"sales_flat_order_item",
		"sales_flat_order_payment",
		"sales_flat_order_status_history",
		"sales_flat_quote",
		"sales_flat_quote_address",
		"sales_flat_quote_item",
		"sales_flat_quote_payment",
		"sales_flat_shipment",
		"sales_flat_shipment_grid",
		"sales_flat_shipment_item",
		"sales_flat_shipment_track",
		"sales_flat_invoice",
		"sales_flat_invoice_grid",
		"sales_flat_invoice_item",
		"sales_flat_creditmemo",
		"sales_flat_creditmemo_grid",
		"sales_flat_creditmemo_item",
		"wishlist",
		"wishlist_item",
	},
	Paths: engine.FrameworkPathConfig{
		LocalMedia:        "media",
		RemoteMedia:       "media",
		WebRootCandidates: []engine.FrameworkWebRootCandidate{},
	},
	Sync: engine.FrameworkSyncConfig{
		NoiseExcludes: []string{
			"var/cache/",
			"var/full_page_cache/",
			"var/session/",
			"var/tmp/",
			"var/log/",
		},
		MediaExcludes: engine.FrameworkMediaExcludeSet{
			NonAll: []string{
				"itm",
				"import",
				"export",
				"importexport",
				"captcha",
				"analytics",
				"custom_options",
				"customer_address",
				"sitemap",
				"catalog_webp",
				"opti_image",
				"webp_image",
				"shoppingfeed",
				"feeds",
				"ftp",
				"lengow",
			},
			Optimized: []string{"catalog/product"},
			Minimal:   []string{"catalog/product"},
		},
	},
	Features: engine.FrameworkFeatureConfig{
		RequiresRunningEnvForFreshInstall: true,
		SupportsPostClone:                 true,
	},
}
