services:
  elasticsearch:
    image: "{{ .ImageRepository }}/elasticsearch:{{ .Config.Stack.SearchVersion }}"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - govard-net

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025"
    networks:
      - govard-net
      - govard-proxy

volumes:
  es-data:
