package deploy

import (
	"fmt"
	"strings"

	"govard/internal/engine"
)

// RenderGitLabPipeline renders stages + one job set per remote from the
// project config. It is pure: no filesystem, network, or container access,
// so tests drive it with in-memory Config values.
//
// The Govard version recorded in the variables block defaults to "dev": the
// command layer (which knows its own build stamp) calls
// RenderGitLabPipelineWithGovardVersion instead.
func RenderGitLabPipeline(cfg engine.Config) (string, error) {
	return RenderGitLabPipelineWithGovardVersion(cfg, "dev")
}

// RenderGitLabPipelineWithGovardVersion is RenderGitLabPipeline with the
// Govard version pinned into the variables block. The caller passes the
// version its own binary was stamped with (from the release tag), so the
// generated file never floats and never carries a hard-coded version literal.
func RenderGitLabPipelineWithGovardVersion(cfg engine.Config, govardVersion string) (string, error) {
	names := make([]string, 0, len(cfg.Remotes))
	for name := range cfg.Remotes {
		names = append(names, name)
	}
	engine.SortRemoteNames(names)
	if len(names) == 0 {
		return "", fmt.Errorf("%w: no remotes configured", ErrInvalidConfiguration)
	}
	for _, name := range names {
		if strings.TrimSpace(cfg.Remotes[name].Branch) == "" {
			return "", fmt.Errorf("%w: remote %q has no branch configured", ErrInvalidConfiguration, name)
		}
	}
	var b strings.Builder
	b.WriteString("# Generated by: govard ci generate --provider gitlab -- DO NOT EDIT.\n")
	b.WriteString("stages: [integrity, lint, ship, rollback]\n\n")
	emitCIImage(&b)
	emitCIVariables(&b, govardVersion)
	emitSSHSetup(&b)
	emitCaches(&b)
	emitIntegrity(&b)
	// Lint jobs run once per pipeline, not per remote: they resolve from the
	// first remote's effective settings, so keep ci_lint_* at project level.
	standard, paths := resolveCILint(cfg, cfg.Remotes[names[0]])
	emitLintQuick(&b, standard)
	emitLintCustom(&b, standard, paths)
	for _, name := range names {
		remote := cfg.Remotes[name]
		emitShip(&b, name, remote, effectiveCIMageMode(cfg, remote))
		emitRollback(&b, name, remote)
	}
	return b.String(), nil
}

// RenderGitLabPipelineForTest exposes RenderGitLabPipeline to package tests.
//
// Production: RenderGitLabPipeline / Test wrapper: RenderGitLabPipelineForTest
// / Test location: tests/ci_generate_test.go
func RenderGitLabPipelineForTest(cfg engine.Config) (string, error) {
	return RenderGitLabPipeline(cfg)
}

// effectiveCIMageMode resolves mage_mode for one remote: the remote override
// wins key by key over the project block. Anything but "developer" means the
// production shape (the recipe default is empty, and empty builds statics).
func effectiveCIMageMode(cfg engine.Config, remote engine.RemoteConfig) string {
	merged := cfg.Deploy
	if remote.Deploy != nil {
		merged = mergeDeployConfig(cfg.Deploy, *remote.Deploy)
	}
	return ciSettingString(merged.Settings, "mage_mode", "")
}

// ciLintSettingKeys are the neutral deploy-settings keys the CI emitter
// reads. Frameworks default them in their recipes; projects override them
// under deploy.settings (or per remote). The emitter never names a framework:
// the values arrive through WithCILintDefaults layering.
var ciLintSettingKeys = []string{"ci_lint_phpcs_standard", "ci_lint_paths"}

// WithCILintDefaults returns cfg with the recipe's CI lint defaults filled in
// wherever the project left a key unset. Project settings always win; keys
// the recipe does not default keep the emitter's neutral fallbacks.
func WithCILintDefaults(cfg engine.Config, defaults map[string]any) engine.Config {
	merged := make(map[string]any, len(cfg.Deploy.Settings)+len(ciLintSettingKeys))
	for _, key := range ciLintSettingKeys {
		if value, ok := defaults[key].(string); ok && strings.TrimSpace(value) != "" {
			merged[key] = value
		}
	}
	for key, value := range cfg.Deploy.Settings {
		merged[key] = value
	}
	cfg.Deploy.Settings = merged
	return cfg
}

// resolveCILint resolves the lint inputs for one remote: the remote override
// wins key by key over the project block (which already carries the recipe
// defaults via WithCILintDefaults). The standard falls back to the language
// default; an undeclared scope disables the scoped phpcs line rather than
// guessing a tree no framework owns.
func resolveCILint(cfg engine.Config, remote engine.RemoteConfig) (standard, paths string) {
	merged := cfg.Deploy
	if remote.Deploy != nil {
		merged = mergeDeployConfig(cfg.Deploy, *remote.Deploy)
	}
	return ciSettingString(merged.Settings, "ci_lint_phpcs_standard", "PSR-12"),
		ciSettingString(merged.Settings, "ci_lint_paths", "")
}

func ciSettingString(settings map[string]any, key, fallback string) string {
	if settings == nil {
		return fallback
	}
	if value, ok := settings[key].(string); ok && strings.TrimSpace(value) != "" {
		return strings.TrimSpace(value)
	}
	return fallback
}

func emitCIImage(b *strings.Builder) {
	// The registry path stays out of this public file: the project defines
	// CI_GOVARD_IMAGE once (digest-pinned) in its GitLab CI/CD variables.
	b.WriteString("# Every job runs in one internal image: PHP + Composer + Node + rsync + govard.\n")
	b.WriteString("image: $CI_GOVARD_IMAGE\n\n")
}

func emitCIVariables(b *strings.Builder, govardVersion string) {
	b.WriteString("variables:\n")
	fmt.Fprintf(b, "  # Pinned by `govard ci generate` from the binary that rendered this file:\n")
	fmt.Fprintf(b, "  # the job image must bundle this Govard version. Regenerate after upgrading.\n")
	fmt.Fprintf(b, "  GOVARD_VERSION: %q\n", govardVersion)
	b.WriteString("  COMPOSER_CACHE_DIR: \"$CI_PROJECT_DIR/.composer-cache\"\n")
	b.WriteString("  NPM_CONFIG_CACHE: \"$CI_PROJECT_DIR/.npm-cache\"\n")
	b.WriteString("  # Speed flags proven on the reference project: fast zip handling\n")
	b.WriteString("  # and minimal compression for caches and artifacts.\n")
	b.WriteString("  FF_USE_FASTZIP: \"true\"\n")
	b.WriteString("  CACHE_COMPRESSION_LEVEL: \"fastest\"\n")
	b.WriteString("  ARTIFACT_COMPRESSION_LEVEL: \"fastest\"\n\n")
}

// emitSSHSetup mirrors the reference project's ssh lines: ssh-agent plus the
// two secret names. Values never appear here, only their names.
func emitSSHSetup(b *strings.Builder) {
	b.WriteString(".ssh_setup: &ssh_setup\n")
	b.WriteString("  - \"command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )\"\n")
	b.WriteString("  - eval $(ssh-agent -s)\n")
	b.WriteString("  - mkdir -p ~/.ssh\n")
	b.WriteString("  - touch ~/.ssh/known_hosts\n")
	b.WriteString("  - echo \"$SSH_KEY\" | tr -d '\\r' | ssh-add -\n")
	b.WriteString("  - chmod 700 ~/.ssh\n")
	b.WriteString("  - echo \"$SSH_KNOWN_HOSTS\" > ~/.ssh/known_hosts\n\n")
}

// emitCaches defines the two cache anchors: composer keyed by its lock file
// (a lock change busts the cache instead of snowballing it), npm by its own.
func emitCaches(b *strings.Builder) {
	b.WriteString(".composer_cache: &composer_cache\n")
	b.WriteString("  key:\n")
	b.WriteString("    files:\n")
	b.WriteString("      - composer.lock\n")
	b.WriteString("    prefix: ${CI_PROJECT_PATH_SLUG}\n")
	b.WriteString("  fallback_keys:\n")
	b.WriteString("    - ${CI_PROJECT_PATH_SLUG}-composer-default\n")
	b.WriteString("  paths:\n")
	b.WriteString("    - .composer-cache/\n")
	b.WriteString("  policy: pull-push\n\n")
	b.WriteString(".npm_cache: &npm_cache\n")
	b.WriteString("  key:\n")
	b.WriteString("    files:\n")
	b.WriteString("      - '**/package-lock.json'\n")
	b.WriteString("    prefix: ${CI_PROJECT_PATH_SLUG}-npm\n")
	b.WriteString("  paths:\n")
	b.WriteString("    - .npm-cache/\n")
	b.WriteString("  policy: pull-push\n\n")
}

func emitIntegrity(b *strings.Builder) {
	b.WriteString("integrity:\n")
	b.WriteString("  stage: integrity\n")
	b.WriteString("  script:\n")
	b.WriteString("    - govard version\n")
	b.WriteString("    - govard audit run --checks integrity --format json\n\n")
}

// emitLintQuick runs on merge requests only: phpcs over the changed PHP
// files (warnings never fail the job) plus phpstan per the repo config with
// a GitLab codequality report.
func emitLintQuick(b *strings.Builder, standard string) {
	b.WriteString("lint:quick:\n")
	b.WriteString("  stage: lint\n")
	b.WriteString("  cache: *composer_cache\n")
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_PIPELINE_SOURCE == \"merge_request_event\"\n")
	b.WriteString("  before_script:\n")
	b.WriteString("    - composer install --prefer-dist --no-progress --no-interaction --no-dev\n")
	b.WriteString("  script:\n")
	b.WriteString("    - |\n")
	b.WriteString("      files=$(git diff --name-only --diff-filter=ACMRT \"$CI_MERGE_REQUEST_DIFF_BASE_SHA...$CI_COMMIT_SHA\" -- '*.php' '*.phtml' | grep -v -e '^vendor/' -e '^generated/' -e '^var/' -e '^pub/media/' || true)\n")
	fmt.Fprintf(b, "      if [ -n \"$files\" ]; then echo \"$files\" | xargs phpcs --standard=%s --runtime-set ignore_warnings_on_exit 1 -p; else echo 'No PHP files changed.'; fi\n", standard)
	b.WriteString("    - phpstan analyse --memory-limit=2G --no-progress --error-format=gitlab > phpstan-gitlab.json\n")
	b.WriteString("  artifacts:\n")
	b.WriteString("    when: always\n")
	b.WriteString("    reports:\n")
	b.WriteString("      codequality: phpstan-gitlab.json\n\n")
}

// emitLintCustom covers the scoped tree on demand and on schedule: the deep
// tier the quick MR gate deliberately skips. An empty scope disables the
// phpcs line (phpstan still runs) rather than scanning a tree no one owns.
func emitLintCustom(b *strings.Builder, standard, paths string) {
	b.WriteString("lint:custom:\n")
	b.WriteString("  stage: lint\n")
	b.WriteString("  cache: *composer_cache\n")
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_PIPELINE_SOURCE == \"schedule\"\n")
	b.WriteString("    - when: manual\n")
	b.WriteString("  before_script:\n")
	b.WriteString("    - composer install --prefer-dist --no-progress --no-interaction --no-dev\n")
	b.WriteString("  script:\n")
	if strings.TrimSpace(paths) != "" {
		fmt.Fprintf(b, "    - phpcs --standard=%s --runtime-set ignore_warnings_on_exit 1 -p %s\n", standard, strings.TrimSpace(paths))
	}
	b.WriteString("    - phpstan analyse --memory-limit=2G --no-progress --error-format=gitlab > phpstan-gitlab.json\n")
	b.WriteString("  artifacts:\n")
	b.WriteString("    when: always\n")
	b.WriteString("    reports:\n")
	b.WriteString("      codequality: phpstan-gitlab.json\n\n")
}

// emitShip renders one single-job ship per remote: developer mode deploys
// straight from the server build, any other mode builds an artifact and
// deploys it inside the same job workspace (no inter-job transfer).
func emitShip(b *strings.Builder, name string, remote engine.RemoteConfig, mageMode string) {
	branch := strings.TrimSpace(remote.Branch)
	fmt.Fprintf(b, "ship:%s:\n  stage: ship\n  resource_group: %s\n", name, name)
	fmt.Fprintf(b, "  rules:\n    - if: $CI_COMMIT_BRANCH == %q\n", branch)
	if !strings.EqualFold(mageMode, "developer") {
		b.WriteString("  cache: *composer_cache\n")
	}
	b.WriteString("  before_script:\n")
	b.WriteString("    - *ssh_setup\n")
	b.WriteString("  script:\n")
	b.WriteString("    - govard version\n")
	if strings.EqualFold(mageMode, "developer") {
		fmt.Fprintf(b, "    - govard deploy --remote %s --revision \"$CI_COMMIT_SHA\" --yes\n", name)
	} else {
		fmt.Fprintf(b, "    - govard deploy build %s --output \"$CI_PROJECT_DIR/artifacts\" --revision \"$CI_COMMIT_SHA\"\n", name)
		fmt.Fprintf(b, "    - govard deploy %s --artifact-dir \"$CI_PROJECT_DIR/artifacts\" --revision \"$CI_COMMIT_SHA\" --yes\n", name)
	}
	fmt.Fprintf(b, "  environment:\n    name: %s\n\n", name)
}

func emitRollback(b *strings.Builder, name string, remote engine.RemoteConfig) {
	branch := strings.TrimSpace(remote.Branch)
	fmt.Fprintf(b, "rollback:%s:\n  stage: rollback\n  resource_group: %s\n", name, name)
	fmt.Fprintf(b, "  rules:\n    - if: $CI_COMMIT_BRANCH == %q\n      when: manual\n", branch)
	b.WriteString("  before_script:\n")
	b.WriteString("    - *ssh_setup\n")
	b.WriteString("  script:\n")
	fmt.Fprintf(b, "    - govard deploy rollback %s --yes\n\n", name)
}
