map $http_cookie $fastcgi_backend {
    default php:9000;
    ~*XDEBUG_SESSION=${XDEBUG_SESSION_PATTERN} php-debug:9000;
}

resolver 127.0.0.11 ipv6=off valid=30s;

include /etc/nginx/conf.d/mage-run-map.conf;

server {
    listen 80;
    server_name _;
    root ${CONVENTIONS_WORK_DIR};

    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass $fastcgi_backend;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_hide_header Transfer-Encoding;
        include fastcgi_params;
        fastcgi_param HTTPS 'on';
        fastcgi_param MAGE_RUN_CODE $mage_run_code;
        fastcgi_param MAGE_RUN_TYPE $mage_run_type;
    }

    location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|ico|webp|woff|woff2|ttf|eot)$ {
        expires 30d;
        access_log off;
    }

    location ~* ^/(app|includes|lib|media/downloadable|pkginfo|report/config\.xml|var)/ {
        deny all;
    }

    location ~* (\.htaccess$|\.git) {
        deny all;
    }
    ${NGINX_CUSTOM_INCLUDE}
}
