// Code generated by "go generate ./internal/frameworks/..."; DO NOT EDIT.

package frameworks

import (
	"govard/internal/frameworks/cakephp"
	"govard/internal/frameworks/custom"
	"govard/internal/frameworks/django"
	"govard/internal/frameworks/drupal"
	"govard/internal/frameworks/emdash"
	"govard/internal/frameworks/laravel"
	"govard/internal/frameworks/magento1"
	"govard/internal/frameworks/magento2"
	"govard/internal/frameworks/mageos"
	"govard/internal/frameworks/nextjs"
	"govard/internal/frameworks/openmage"
	"govard/internal/frameworks/prestashop"
	"govard/internal/frameworks/shopware"
	"govard/internal/frameworks/symfony"
	"govard/internal/frameworks/types"
	"govard/internal/frameworks/wordpress"
)

func init() {
	RegisterSpecs([]types.FrameworkSpec{
		emdash.Spec(),
		cakephp.Spec(),
		custom.Spec(),
		django.Spec(),
		drupal.Spec(),
		laravel.Spec(),
		magento1.Spec(),
		magento2.Spec(),
		mageos.Spec(),
		nextjs.Spec(),
		openmage.Spec(),
		prestashop.Spec(),
		shopware.Spec(),
		symfony.Spec(),
		wordpress.Spec(),
	})
}
